services:
  test-node-a:
    build:
      context: .
      dockerfile: Dockerfile
    image: xdp-thesis-toolkit:latest
    profiles: ["client"]
    container_name: test-node-a
    command: /bin/sh -c "ethtool -K eth0 tx off && sleep infinity"
    privileged: true
    networks:
      xdp-bridge:
        ipv4_address: 172.20.0.10

  test-node-b:
    image: xdp-thesis-toolkit:latest
    container_name: test-node-b
    profiles: ["server"]
    ports:
      - "8088:5201/tcp"
      - "8088:5201/udp"
    command: /bin/sh -c "ethtool -K eth0 tx off && iperf3 -s -J -p 5201 -D && sleep infinity"
    privileged: true
    networks:
      xdp-bridge:
        ipv4_address: 172.20.0.20

  test-node-c:
    image: xdp-thesis-toolkit:latest
    container_name: test-node-c
    profiles: ["server"]
    ports:
      - "8089:11111/udp"
    command: /bin/sh -c "ethtool -K eth0 tx off && sockperf sr -p 11111 --daemonize && sleep infinity"
    privileged: true
    networks:
      xdp-bridge:
        ipv4_address: 172.20.0.30

  xdp-natd:
    build:
      context: ../
      dockerfile: Dockerfile
    image: xdp-natd:latest
    profiles: ["offload"]
    container_name: xdp-natd
    privileged: true
    network_mode: "host"
    pid: "host"
    environment:
      - RUST_LOG=info
      - APP_ENV=local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/bpf:/sys/fs/bpf
      - /lib/modules:/lib/modules:ro
      - ../configuration/:/configuration:ro

networks:
  xdp-bridge:
    name: br-xdp
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-xdp
    ipam:
      config:
        - subnet: 172.20.0.0/24
